version: 2
jobs:
    build:
        working_directory: ~/spt-maven-parent
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            
            # checkout
            - add_ssh_keys:
                fingerprints:
                    - 00:d2:17:7c:fd:6d:ea:ff:ec:35:e6:e9:10:2d:03:77
            - run: |
                curl -fsSL https://goo.gl/PcfcFG | \
                    bash -s -- /usr/local/bin
            - run: |
                curl -fsSL https://goo.gl/dPhYzo | \
                    bash -s -- https://goo.gl/iQAT3h ${OPENSSL_PASSWORD}
            - run: |
                git-config-user "${GIT_USERNAME}" ${GIT_EMAIL}
            - checkout:
                path: ~/spt-maven-parent
            
            # dependencies
            - restore_cache:
                keys:
                    - cache-{{ .Branch }}
            - run: |
                mvn-settings sonatype ${MAVEN_USERNAME} ${MAVEN_PASSWORD}
                mvn-go-offline
            - save_cache:
                paths:
                    - ~/.m2
                key: cache-{{ .Branch }}
            
            # test
            - run: |
                mvn-test
                if [[ -v RELEASE_VERSION ]]; then
                    mvn-release-prepare ${RELEASE_VERSION}
                    mvn-release-perform \
                        -P gpg -Darguments=-Dgpg.passphrase=${GPG_PASSWORD}
                    git-flow-release-finish ${CIRCLE_BRANCH}
                else
                    mvn-deploy
                fi
